package com.example.agenda_pessoal.Model;


public interface Constants {
    //DON'T CREATE A CONSTANT WITH THE SAME NUMBER
    //REQUESTS
    int LOGIN_ACTIVITY_REQUEST_CODE = 0;
    int REGISTER_ACTIVITY_REQUEST_CODE = 1;
    int EVENT_ACTIVITY_REQUEST_CODE = 2;
    int NEW_EVENT_ACTIVITY_REQUEST_CODE = 3;
    int PROFILE_ACTIVITY_REQUEST_CODE = 4;
    int TASK_ACTIVITY_REQUEST_CODE = 5;



    //RESULTS
    int RESULT_DESTROY = 2;

}

